### ISSUE TITLE
Could not connect to any X display.

### ISSUE THREAD

**Issue by djmuirhead** [ghostop14/sparrow-wifi#19]
I installed the cloned directory and followed instructions to install python3, qt5 and qtchart on a Dell XPS-13 laptop running Ubuntu 18.10. The following error message was returned when I ran "sudo pip3 install QScintilla PyQtChart gps3 dronekit manuf python-dateutil numpy matplotlib"

**The directory '/home/doug/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/doug/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.**

After that everything seemed to install just fine. But when I run "sudo ./sparrow-wifi.py" it returns

**No protocol specified
qt.qpa.screen: QXcbConnection: Could not connect to display :0
Could not connect to any X display.**

Is it the error installing pip3 causing this problem? Do I need to figure out the - H argument for sudo? I am a long time linux user but not real good at the commend line. Any help is appreciated.

**Comment by ghostop14** [comment]
Hi djmuirhead, one thing I've done over the years that generally fixes the permissions issue to try first.  Give this a shot.

cd /home
sudo chown -R doug.doug doug
(That should reset the permissions.  Sometimes the hidden [dotted] directories can be tricky to get the permissions to propogate but that should do the trick).

Then try the sudo pip3 install again.

For the "could not connect to display :0" issue, I've seen that happen in general on Linux in a couple of scenarios, usually when connecting remote.  Try this:
1.  Log in locally to the Ubuntu box (don't VNC or SSH to it to run Sparrow)
2. sudo -i
3. Run sparrow

Here's some scenarios where display :0 issues happen in general on linux:
1. If you're SSH'd to the box and you haven't done the -X flag
2. If you've used the flag but SSH'd as a regular user, then try to sudo <app> a GUI-enabled app
3. If you've VNC'd to a box as a regular user then you try to sudo <app> >.

Generally you can test the display :0 issue with something like gedit to see if it's how you're logged in.  Try running gedit from the command-line the same way you're trying to run sparrow (either sudo ./sparrow-wifi.py or sudo -i then ./sparrow-wifi.py).  If gedit works, then sparrow should come up too provided you're not missing any components.

**Comment by djmuirhead** [comment]
Thanks for your reply. I've got a feeling I may be asking you to diagnose a screwed up machine. No SSH, no VNC, just a Dell laptop operated from it's own keyboard. If I run sparrow-wifi.py without sudo the GUI screen comes up but tells me I need to use sudo for permissions. Try again with sudo and get the same error message as before. (Sudo -i made no difference and was kind of scary.) Same result trying to run gedit. Comes right up if no sudo, error message if I use sudo. I can't fathom why a laptop would be unable to access it's own built-in display just because root permissions are turned on.

If you have any advice please share. If not, thanks anyway.

**Comment by ghostop14** [comment]
It has to do with the way linux handles xsessions.  I run into the display :0 thing every once in a while.  I haven't tested Ubuntu 18 (still running 16 since I trust it).  Wonder if it's a bug in 18 that needs to be fixed.

**Comment by djmuirhead** [comment]
I'll ask over at the Ubuntu forums, then. Thanks again.

**Comment by ghostop14** [comment]
You're welcome

**Comment by honghh2018** [comment]
Hi @All
  i throw the jobs on node1, it get error like below:
  data = yaml.load(f.read()) or {}
qt.qpa.screen: QXcbConnection: Could not connect to display localhost:10.0
Could not connect to any X display.
But the master node can run well.
 For this condition, i want to know how to turn off the X display in all the CENTOS 7.3 server?
  Any kindly help would be appreciated.
   hanhuihong

**Comment by honghh2018** [comment]
The python program trigger this error.

**Comment by ghostop14** [comment]
Hi honghh2018,  I'm not sure what the message is related to?  That code isn't in sparrow wifi.  Sounds like your issue may be more appropriate for an X display or CENTOS forum?

**Comment by ghostop14** [comment]
It sounds like you're running remote or something.  Take a look at xhost's options to authorize a device.  You may need to do something like "xhost +localhost" on the command line if it's complaining about localhost.

**Comment by honghh2018** [comment]
Thanks @ghostop14,
         This error seem like a occasion error. when i rerun it, it work well withdout the same error.
It was unfortunate to hearing this error like this condition
