### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by rikosintie** [ghostop14/sparrow-wifi#26]
Hello, I am running Ubuntu 18.04 and this tool is fantastic! I have an Ubertooth One and it works perfectly with it.

Is there any way to donate to the project?

If not, do you have any documentation you need to be created? Or other non dev work?

Thanks!

**Comment by ghostop14** [comment]
Hi rikosintie, thanks for the support!  For the moment I think I'm good.  There are some future / requested tech items I've considered but for the moment I think the project is pretty stable.

**Comment by rikosintie** [comment]
I agree!  If you need anything in the future let me know.
