### ISSUE TITLE
Is this repository dead?

### ISSUE THREAD

**Issue by stryngs** [ghostop14/sparrow-wifi#41]
If this repository is no longer maintained how do we kick something off with it?

**Comment by stryngs** [comment]
@ghostop14 @jkbecker Hello.

**Comment by ghostop14** [comment]
Hey stryngs.  Nope it's not dead.  Just pushed a few weeks ago for some elasticsearch integration.  Just been traveling a lot for work the past month.

**Comment by stryngs** [comment]
Rah rah, go PR go
