### ISSUE TITLE
[Feature Request] Web Server Interface?

### ISSUE THREAD

**Issue by heywoodlh** [ghostop14/sparrow-wifi#5]
Is there any way this could be served via web server vs on the desktop? I think a headless setup would be nice.

**Comment by ghostop14** [comment]
Actually if you look at the agent, it just responds to get and post requests in the SparrowWiFiAgentRequestHandler class in sparrowwifiagent.  You could easily wrap an HTML page with some javascript around the calls and completely web-enable it.  Or even call the API's from your own code.  For instance with the agent running a call to http://<agent ip>/wireless/interfaces will return JSON with the wireless interfaces on the system.

**Comment by heywoodlh** [comment]
That is awesome, thanks for the info!

**Comment by ghostop14** [comment]
You're welcome!
