### ISSUE TITLE
CAN-U-RECREATE-THIS-FOR-WINDOWS

### ISSUE THREAD

**Issue by morpheuslord** [ghostop14/sparrow-wifi#58]
hello 

my name is morpheuslord
i am a hacker and i use mostly windows and pentestbox as my main tool so i wanted to ask if u can remake this for windows

thank you
morpheuslord

**Comment by ghostop14** [comment]
Hi morpheuslord, the underlying mechanisms are fundamentally different for Windows and Linux.  My suggestion to run under linux is to use VMWare or Docker and run a Kali linux build.  Then use a USB-based wifi adapter and you should be all set.
