### ISSUE TITLE
(Request/Question) Influxdb and Grafana Agent

### ISSUE THREAD

**Issue by alphafox02** [ghostop14/sparrow-wifi#65]
After setting up Influxdb and Grafana for RTL433 it reminded me of the elastic agent built for sparrow-wifi. Would it be possible to manipulate sparrow-wifi's data and push it into the same setup? 

I have the sparrow-wifi agent running on the PinePhone, but thought it would be better to have the info going into Influxdb/Grafana along with the rtl433 information.

**Comment by ghostop14** [comment]
Hi alphafox02, sure I don't see why not.  I've never used influxdb before but it looks like there's a python module for it.  I'd suggest just taking the elastic one as your template, and swap out the elastic stuff for influxdb as needed for your app.
